Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6085669497913895679">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6085669497913895679">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20151224055819

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6088206216156930376">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6088206216156930376">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20151231055826

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6090742929031693970">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6090742929031693970">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160107055825

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6100889789786544084">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6100889789786544084">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160204055841

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6105963217151680515">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6105963217151680515">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160218055843

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6111036654654228857">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6111036654654228857">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160303055836

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6113573361863357537">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6113573361863357537">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160310055845

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6116110083109149654">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6116110083109149654">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160317055845

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6121183508486415804">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6121183508486415804">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160331055845

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6126256947276474547">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6126256947276474547">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160414055905

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6128793653841358929">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6128793653841358929">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160421055903

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6131330376553440234">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6131330376553440234">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160428055848

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6133867084735508638">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6133867084735508638">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160505055925

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6138940514795506308">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6138940514795506308">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160519055858

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6141477235348971956">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6141477235348971956">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160526055909

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6146550662458285614">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6146550662458285614">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160609055903

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6149087372239448344">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6149087372239448344">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160616055908

Procfile, app.json, bin/run.sh
* add buildpack-webpack into app.json
* run puma web server directly in Procfile
=> use buildpack-webpack

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6161770953130318038">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6161770953130318038">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160721055807

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6164307671871266893">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6164307671871266893">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160728055809

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6171917817253734912">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6171917817253734912">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160818055812

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6179527954919264993">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6179527954919264993">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160908055814

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6182064668187847336">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6182064668187847336">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160915055814

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6184601384230439321">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6184601384230439321">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160922055815

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6189674819517352782">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6189674819517352782">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161006055820

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6192211537137208022">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6192211537137208022">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161013055830

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6197284961591147626">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6197284961591147626">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161027055823

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6199821680068575267">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6199821680068575267">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161103055837

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6204895107847688730">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6204895107847688730">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161117055829

.travis.yml, Gemfile, Gemfile.lock, package.json
* rewrite ruby 2.3.1 to 2.3.3 or '~> 2.3.0'
* ncu -u && npm update
=> update packages: ruby 2.3.3 and npms

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6207431826134754668">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6207431826134754668">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161124055830

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6209968542325485536">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6209968542325485536">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161201055837

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6212505257316121818">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6212505257316121818">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161208055842

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6222652112250825075">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6222652112250825075">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170105055803

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6225188824808000632">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6225188824808000632">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170112055803

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6227725543502427291">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6227725543502427291">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170119055804

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6232798970671992781">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6232798970671992781">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170202055805

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6235335684717959208">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6235335684717959208">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170209055803

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6237872401670926946">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6237872401670926946">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170216055804

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6240409117879240471">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6240409117879240471">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170223055804

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6242945830309687841">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6242945830309687841">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170302055804

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6248019259279258033">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6248019259279258033">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170316055803

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6250555977938415839">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6250555977938415839">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170323055804

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6255629406930112554">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6255629406930112554">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170406055803

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6263239554164520118">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6263239554164520118">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170427055803

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6265776270059644421">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6265776270059644421">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170504055803

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6270849694685792742">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6270849694685792742">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170518055803

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6275923128816237515">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6275923128816237515">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170601055804

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6283533270260691964">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6283533270260691964">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170622055803

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6286069986530322841">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6286069986530322841">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170629055802

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6319543259444849491">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6319543259444849491">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170929144853

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6322079978579493342">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6322079978579493342">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171006144855

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6324616692151693021">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6324616692151693021">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171013144854

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6329690127343413167">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6329690127343413167">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171027144855

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6332226835738106736">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6332226835738106736">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171103144852

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6334763554387695408">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6334763554387695408">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171110144854

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6337300273635453667">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6337300273635453667">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171117144856

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6339836982906575007">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6339836982906575007">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171124144853

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6347447130224806260">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6347447130224806260">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171215144856

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6349983839429851872">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6349983839429851872">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171222144854

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6357593988135599785">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6357593988135599785">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180112144853

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6375350994685614610">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6375350994685614610">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180302144855

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6382961140342846367">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6382961140342846367">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180323144854

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6385497851454213029">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6385497851454213029">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180330144853

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6388034568981067773">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6388034568981067773">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180406144854

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6390571282343596261">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6390571282343596261">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180413144854

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6393108001910824599">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6393108001910824599">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180420144854

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6400718147006956335">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6400718147006956335">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180511144854
